### ISSUE TITLE
eip-4824 singleton?

### ISSUE THREAD

**Issue by z0r0z** [metagov/daostar#19]
can we add a function for `daoURI(address)` to the standard?

Basically, having a variant of `daoURI()` with an `address` that returns a `string`.

This would allow a singleton registry for all daos rather than creating a registration contract for every single dao.

**Comment by thelastjosh** [comment]
Adding @ipatka here.

> This would allow a singleton registry for all daos rather than creating a registration contract for every single dao.
Currently our assumption is that we would use the factory contract to index / create a registry of all DAOs. Part of the reason here is because we didn't want there to be a single source of truth for registering all DAOs (so others could deploy their own registries), but still make it convenient to have a way of indexing a lot of DAOs. I think having a separate registration/management contract is still important for managing daoURI.

That said, we're already talking about having the ability to submit multiple contract addresses in the registration contract (so a single registration contract could manage the APIs of multiple contracts), so this proposal would be a good thing to discuss at the next strike team meeting at 11am ET on Thursdays.

Separate subject, but I could also imagine adding an address field of some sort to the daoURI JSON schema for various reasons.

**Comment by thelastjosh** [comment]
Note that @ipatka recently merged a PR that allows submitting of multiple contract addresses!
